CarLoanApplication/Controllers/CarLoanController.cs
using CarLoanApplication.Models;
using CarLoanApplication.Models.APIResponse;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;

namespace CarLoanApplication.Controllers
{
    public class CarLoanController : Controller
    {
        // GET: CarLoan
        public ActionResult Index()
        {
            var details = new CarLoanApp();

            return View(details);
        }

        [HttpPost]
        public ActionResult Add(CarLoanApp app)
        {
            var RequestAPI = app;
            string APIResponse = string.Empty;
            HttpResponseMessage APIResponseMessage = new HttpResponseMessage();
            // var ReturnResponse = (T)Activator.CreateInstance(typeof(T));
            try
            {
                HttpClientHandler clientHandler = new HttpClientHandler();
                //    clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
                clientHandler.Proxy = null;
                var httpClientHandler = new HttpClientHandler() { Proxy = null };
                using (HttpClient client = new HttpClient(clientHandler))
                {
                    client.BaseAddress = new Uri("https://localhost:7268/api/CarLoanApplicationAPI/Add");
                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                    ByteArrayContent ByteContent = null;
                    if (RequestAPI != null)
                    {
                        var ContentBody = JsonConvert.SerializeObject(RequestAPI);
                        var buffer = System.Text.Encoding.UTF8.GetBytes(ContentBody);
                        ByteContent = new ByteArrayContent(buffer);
                        ByteContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
                    }

                    APIResponseMessage = client.PostAsync("https://localhost:7268/api/CarLoanApplicationAPI/Add", ByteContent).Result;


                    APIResponse = APIResponseMessage.Content.ReadAsStringAsync().Result;
                    var respo = JsonConvert.DeserializeObject<Models.APIResponse.AddFormResponse>(APIResponse);
                }
            }
            catch (Exception ex)
            {

            }
            finally
            {

            }
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult List()
        {
            ListResponse listResponse = new ListResponse();
            string ApiResponse = string.Empty;
            HttpResponseMessage httpResponse = new HttpResponseMessage();
            try
            {
                HttpClientHandler clientHandler = new HttpClientHandler();
                clientHandler.Proxy = null;
                using (HttpClient client = new HttpClient(clientHandler))
                {
                    client.BaseAddress = new Uri("https://localhost:7268/api/CarLoanApplicationAPI/ApplicantList");
                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;



                    httpResponse = client.GetAsync("https://localhost:7268/api/CarLoanApplicationAPI/ApplicantList").Result;
                    ApiResponse = httpResponse.Content.ReadAsStringAsync().Result;
                    listResponse = JsonConvert.DeserializeObject<Models.APIResponse.ListResponse>(ApiResponse);
                }
            }
            catch (Exception ex)
            {

            }
            finally
            {

            }
            return View(listResponse);
        }

        public ActionResult Details(string LoanId)
        {
            var RequestAPI = LoanId;
            string ApiResponse = string.Empty;
            HttpResponseMessage APIResponseMessage = new HttpResponseMessage();
            try
            {
                HttpClientHandler clientHandler = new HttpClientHandler();
                clientHandler.Proxy = null;
                var httpClientHandler = new HttpClientHandler() { Proxy = null };
                using (HttpClient client = new HttpClient(clientHandler))
                {
                    client.BaseAddress = new Uri("https://localhost:7268/api/CarLoanApplicationAPI/Details?LoanId=" + LoanId);
                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                    ByteArrayContent ByteContent = null;
                    if (RequestAPI != null)
                    {
                        var ContentBody = JsonConvert.SerializeObject(RequestAPI);
                        var buffer = System.Text.Encoding.UTF8.GetBytes(ContentBody);
                        ByteContent = new ByteArrayContent(buffer);
                        ByteContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
                    }

                    APIResponseMessage = client.PostAsync("https://localhost:7268/api/CarLoanApplicationAPI/Details?LoanId=" + LoanId, ByteContent).Result;
                    ApiResponse = APIResponseMessage.Content.ReadAsStringAsync().Result;
                    var respo = JsonConvert.DeserializeObject<Models.APIResponse.DetailApiResponse>(ApiResponse);

                    
                    return View(respo);
                }
            }
            catch (Exception ex)
            {

            }
            finally
            {

            }
            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Update(DetailApiResponse request)
        {
            APIUpdateRequest aPIUpdate = new APIUpdateRequest();
            aPIUpdate.updatePersonadetail = new APIUpdateRequest.UpdatePersonalDetail
            {
                loanId = request.data.result.loanId,
                firstName = request.data.result.firstName,
                lastName = request.data.result.lastName,
                birthDate = request.data.result.birthDate,
                maritalStatus = request.data.result.maritalStatus,
                email = request.data.result.email,
                phoneNumber = request.data.result.phoneNumber,
                emergencyContactNumber = request.data.result.emergencyContactNumber,
                driversLicenseNumber = request.data.result.driversLicenseNumber
            };
            aPIUpdate.updateAddressdetail = new APIUpdateRequest.UpdateAddressDetail
            {
                addressLine1 = request.data.result.addressLine1,
                addressLine2 = request.data.result.addressLine2,
                city = request.data.result.city,
                state = request.data.result.state,
                postalCode = request.data.result.postalCode
            };
            aPIUpdate.updateFinancialdetail = new APIUpdateRequest.UpdateFinancialDetail
            {
                bankName = request.data.result.bankName,
                branch = request.data.result.branch,
                accountType = request.data.result.accountType,
                accountNumber = request.data.result.accountNumber,
                ownOrRent = request.data.result.ownOrRent,
                currentLoan = request.data.result.currentLoan,
                workingStatus = request.data.result.workingStatus,
                monthlyIncome = request.data.result.monthlyIncome
            };
            aPIUpdate.updateVehicaldetail = new APIUpdateRequest.UpdateVehicalDetail
            {
                makeAndModel = request.data.result.makeAndModel,
                variant = request.data.result.variant,
                registeredDate = request.data.result.registeredDate,
                mileage = request.data.result.mileage,
                insurance = request.data.result.insurance,
                registrationNumber = request.data.result.registrationNumber,
                nEWorSECONDHAND = request.data.result.nEWorSECONDHAND,
                hpi = request.data.result.hpi,
                fullPrice = request.data.result.fullPrice
            };
            aPIUpdate.updateRequestedloandetail = new APIUpdateRequest.UpdateRequestedLoanDetail
            {
                carType = request.data.result.carType,
                loanAmount = request.data.result.loanAmount,
                terms = request.data.result.terms,
                prefferedPayment = request.data.result.prefferedPayment,
                coSigner = request.data.result.coSigner,
                coSignerName = request.data.result.coSignerName,
                coSignerPhoneNo = request.data.result.coSignerPhoneNo
            };

            var RequestApi = aPIUpdate;
            string ApiResponse = string.Empty;
            HttpResponseMessage APIResponseMessage = new HttpResponseMessage();
            try
            {
                HttpClientHandler ClientHandler = new HttpClientHandler();
                ClientHandler.Proxy = null;
                var httpClientHandler = new HttpClientHandler() { Proxy = null };
                using (HttpClient Client = new HttpClient(httpClientHandler))
                {
                    Client.BaseAddress = new Uri("https://localhost:7268/api/CarLoanApplicationAPI/Update");
                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                    ByteArrayContent bytecontent = null;
                    if (RequestApi != null)
                    {
                        var ContentBody = JsonConvert.SerializeObject(RequestApi);
                        var buffer = System.Text.Encoding.UTF8.GetBytes(ContentBody);
                        bytecontent = new ByteArrayContent(buffer);
                        bytecontent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
                    }

CarLoanApplication/Views/CarLoan/Details.cshtml
@model CarLoanApplication.Models.APIResponse.DetailApiResponse
@using System.Data;
@{
    ViewBag.Title = "Details";
}

<h2>Update</h2>

@using (Html.BeginForm("Update", "CarLoan", FormMethod.Post))
{
    @Html.HiddenFor(x => x.data.result.loanId)
    <br />
    <h4>PERSONAL DETAILS</h4>
    @Html.LabelFor(x => x.data.result.firstName)
    @Html.TextBoxFor(x => x.data.result.firstName)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.lastName)
    @Html.TextBoxFor(x => x.data.result.lastName)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.birthDate)
    @Html.TextBoxFor(x => x.data.result.birthDate, new{ @type = "Date", @Value = Model.data.result.birthDate.ToString("yyyy-MM-dd") })
    <br />
    <br />
    <b> Select Marital Status</b>
    <br />
    <span> Married : @Html.RadioButtonFor(x => x.data.result.maritalStatus, "Married") </span>
    <span> Single :  @Html.RadioButtonFor(x => x.data.result.maritalStatus, "Single") </span>
    <span> Divorced :  @Html.RadioButtonFor(x => x.data.result.maritalStatus, "Divorced") </span>
    <span> Widowed :  @Html.RadioButtonFor(x => x.data.result.maritalStatus, "Widowed") </span>
    <span> Seperated :  @Html.RadioButtonFor(x => x.data.result.maritalStatus, "Seperated") </span>
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.email)
    @Html.TextBoxFor(x => x.data.result.email)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.phoneNumber)
    @Html.TextBoxFor(x => x.data.result.phoneNumber)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.emergencyContactNumber)
    @Html.TextBoxFor(x => x.data.result.emergencyContactNumber)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.driversLicenseNumber)
    @Html.TextBoxFor(x => x.data.result.driversLicenseNumber)
    <br />
    <br />
    <h4>ADDRESS DETAILS</h4>
    @Html.LabelFor(x => x.data.result.addressLine1)
    @Html.TextBoxFor(x => x.data.result.addressLine1)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.addressLine2)
    @Html.TextBoxFor(x => x.data.result.addressLine2)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.city)
    @Html.TextBoxFor(x => x.data.result.city)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.state)
    @Html.TextBoxFor(x => x.data.result.state)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.postalCode)
    @Html.TextBoxFor(x => x.data.result.postalCode)
    <br />
    <br />
    <h4>FINANCIAL DETAILS</h4>
    @Html.LabelFor(x => x.data.result.bankName)
    @Html.TextBoxFor(x => x.data.result.bankName)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.branch)
    @Html.TextBoxFor(x => x.data.result.branch)
    <br />
    <br />
    <b>Select Account Type</b>
    <br />
    <span> Savings : @Html.RadioButtonFor(x => x.data.result.accountType, "Savings")</span>
    <span> Current : @Html.RadioButtonFor(x => x.data.result.accountType, "Current")</span>
    <span> Salary : @Html.RadioButtonFor(x => x.data.result.accountType, "Salary")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.accountNumber)
    @Html.TextBoxFor(x => x.data.result.accountNumber)
    <br />
    <br />
    <b>Owned house or Rented house?</b>
    <br />
    <span> Owned : @Html.RadioButtonFor(x => x.data.result.ownOrRent, "Owned")</span>
    <span> Rented : @Html.RadioButtonFor(x => x.data.result.ownOrRent, "Rented")</span>
    <br />
    <br />
    <b>Any Ongoing Loan?</b>
    <br />
    <span> Yes : @Html.RadioButtonFor(x => x.data.result.currentLoan, "Yes")</span>
    <span> No : @Html.RadioButtonFor(x => x.data.result.currentLoan, "No")</span>
    <br />
    <br />
    <b>Currently Working?</b>
    <br />
    <span> Yes : @Html.RadioButtonFor(x => x.data.result.workingStatus, "Yes")</span>
    <span> No : @Html.RadioButtonFor(x => x.data.result.workingStatus, "No")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.monthlyIncome)
    @Html.TextBoxFor(x => x.data.result.monthlyIncome)
    <br />
    <br />
    <h4>VEHICAL DETAILS</h4>
    @Html.LabelFor(x => x.data.result.makeAndModel)
    @Html.TextBoxFor(x => x.data.result.makeAndModel)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.variant)
    @Html.TextBoxFor(x => x.data.result.variant)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.registeredDate)
    @Html.TextBoxFor(x => x.data.result.registeredDate, new { @type = "Date", @Value = Model.data.result.registeredDate.ToString("yyyy-MM-dd") })
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.mileage)
    @Html.TextBoxFor(x => x.data.result.mileage)
    <br />
    <br />
    <b>Is your vehical Insured?</b>
    <br />
    <span> Yes : @Html.RadioButtonFor(x => x.data.result.insurance, "Yes")</span>
    <span> No : @Html.RadioButtonFor(x => x.data.result.insurance, "No")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.registrationNumber)
    @Html.TextBoxFor(x => x.data.result.registrationNumber)
    <br />
    <br />
    <b>Which hand vehical you are using?</b>
    <br />
    <span> FirstHand : @Html.RadioButtonFor(x => x.data.result.nEWorSECONDHAND, "FirstHand")</span>
    <span> SecondHand : @Html.RadioButtonFor(x => x.data.result.nEWorSECONDHAND, "SecondHand")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.hpi)
    @Html.TextBoxFor(x => x.data.result.hpi)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.fullPrice)
    @Html.TextBoxFor(x => x.data.result.fullPrice)
    <br />
    <br />
    <h4>REQUESTED LOAN DETAILS</h4>
    <b>Select Loan Type</b>
    <br />
    <span> UsedCar : @Html.RadioButtonFor(x => x.data.result.carType, "UsedCar")</span>
    <span> NewCar : @Html.RadioButtonFor(x => x.data.result.carType, "NewCar")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.loanAmount)
    @Html.TextBoxFor(x => x.data.result.loanAmount)
    <br />
    <br />
    <b>Select Term Duration</b>
    <br />
    <span> OneYear : @Html.RadioButtonFor(x => x.data.result.terms, "OneYear")</span>
    <span> TwoYear : @Html.RadioButtonFor(x => x.data.result.terms, "TwoYear")</span>
    <span> ThreeYear : @Html.RadioButtonFor(x => x.data.result.terms, "ThreeYear")</span>
    <span> FourYear : @Html.RadioButtonFor(x => x.data.result.terms, "FourYear")</span>
    <br />
    <br />
    <b>Select Prefered Payment</b>
    <br />
    <span> Monthly : @Html.RadioButtonFor(x => x.data.result.prefferedPayment, "Monthly")</span>
    <span> Quarterly : @Html.RadioButtonFor(x => x.data.result.prefferedPayment, "Quartly")</span>
    <span> Yearly : @Html.RadioButtonFor(x => x.data.result.prefferedPayment, "Yearly")</span>
    <br />
    <br />
    <b>Do you have a Co-signer?</b>
    <br />
    <span> Yes : @Html.RadioButtonFor(x => x.data.result.coSigner, "Yes")</span>
    <span> No : @Html.RadioButtonFor(x => x.data.result.coSigner, "No")</span>
    <br />
    <br />
    <b>If yes then fill below</b>
    <br />
    @Html.LabelFor(x => x.data.result.coSignerName)
    @Html.TextBoxFor(x => x.data.result.coSignerName)
    <br />
    <br />
    @Html.LabelFor(x => x.data.result.coSignerPhoneNo)
    @Html.TextBoxFor(x => x.data.result.coSignerPhoneNo)
    <br />
    <br />
    <input type="submit" value="Update" />
}

CarLoanApplication/Views/CarLoan/InActiveList.cshtml
@model CarLoanApplication.Models.APIResponse.ListResponse
@using System.Data;

@{
    ViewBag.Title = "InActive List";
}

<a href="@Url.Action("Index")" class="btn btn-primary">Add</a>
<h2>Active Loan Applicant List</h2>
@using (Html.BeginForm("SearchList", "CarLoan", FormMethod.Get))
{
    @Html.TextBox("Search")
    <input type="submit" value="search " />

}
<table class="table">
    <thead>
        <tr>
            <td scope="col">
                <h5>FirstName</h5>
            </td>
            <td scope="col">
                <h5>LastName</h5>
            </td>
            <td scope="col">
                <h5>BirthDate</h5>
            </td>
            <td scope="col">
                <h5>MaritalStatus</h5>
            </td>
            <td scope="col">
                <h5>Email</h5>
            </td>
            <td scope="col">
                <h5>CarType</h5>
            </td>
            <td scope="col">
                <h5>LoanAmount</h5>
            </td>
            <td scope="col">
                <h5>Activity</h5>
            </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var L in Model.loanApplicantLists)
        {
            if (L.status == false)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("Details", new { LoanId = L.loanId })"> @L.firstName </a>
                    </td>
                    <td>
                        @L.lastName
                    </td>
                    <td>
                        @L.birthDate
                    </td>
                    <td>
                        @L.maritalStatus
                    </td>
                    <td>
                        @L.email
                    </td>
                    <td>
                        @L.loanType
                    </td>
                    <td>
                        @L.loanAmount
                    </td>
                    @if (L.status == true)
                    {
                        <td>
                           <h6>Active</h6>
                        </td>
                    }
                    @if (L.status == false)
                    {
                        <td>
                           <h6>InActive</h6>
                        </td>
                        <td>
                            <a href="@Url.Action("Active", new { LoanId = L.loanId, L.status })" class="btn btn-success"> Active </a>
                        </td>
                    }
                </tr>
            }

        }
    </tbody>
</table>

CarLoanApplication/Views/CarLoan/Index.cshtml
@model CarLoanApplication.Models.CarLoanApp
@using System.Data;
@{
    ViewBag.Title = "Index";
}

<h2>CAR LOAN APPLICATION</h2>

@using (Html.BeginForm("Add", "CarLoan", FormMethod.Post))
{
    <h4>PERSONAL DETAILS</h4>
    @Html.LabelFor(x => x.personadetail.firstName)
    @Html.TextBoxFor(x => x.personadetail.firstName)
    <br />
    <br />
    @Html.LabelFor(x => x.personadetail.lastName)
    @Html.TextBoxFor(x => x.personadetail.lastName)
    <br />
    <br />
    @Html.LabelFor(x => x.personadetail.birthDate)
    @Html.TextBoxFor(x => x.personadetail.birthDate, new { @type = "Date" })
    <br />
    <br />
    <b> Select Marital Status</b>
    <br />
    <span> Married : @Html.RadioButtonFor(x => x.personadetail.maritalStatus, "Married") </span>
    <span> Single :  @Html.RadioButtonFor(x => x.personadetail.maritalStatus, "Single") </span>
    <span> Divorced :  @Html.RadioButtonFor(x => x.personadetail.maritalStatus, "Divorced") </span>
    <span> Widowed :  @Html.RadioButtonFor(x => x.personadetail.maritalStatus, "Widowed") </span>
    <span> Seperated :  @Html.RadioButtonFor(x => x.personadetail.maritalStatus, "Seperated") </span>
    <br />
    <br />
    @Html.LabelFor(x => x.personadetail.email)
    @Html.TextBoxFor(x => x.personadetail.email)
    <br />
    <br />
    @Html.LabelFor(x => x.personadetail.phoneNumber)
    @Html.TextBoxFor(x => x.personadetail.phoneNumber)
    <br />
    <br />
    @Html.LabelFor(x => x.personadetail.emergencyContactNumber)
    @Html.TextBoxFor(x => x.personadetail.emergencyContactNumber)
    <br />
    <br />
    @Html.LabelFor(x => x.personadetail.driversLicenseNumber)
    @Html.TextBoxFor(x => x.personadetail.driversLicenseNumber)
    <br />
    <br />
    <h4>ADDRESS DETAILS</h4>
    @Html.LabelFor(x => x.addressdetail.addressLine1)
    @Html.TextBoxFor(x => x.addressdetail.addressLine1)
    <br />
    <br />
    @Html.LabelFor(x => x.addressdetail.addressLine2)
    @Html.TextBoxFor(x => x.addressdetail.addressLine2)
    <br />
    <br />
    @Html.LabelFor(x => x.addressdetail.city)
    @Html.TextBoxFor(x => x.addressdetail.city)
    <br />
    <br />
    @Html.LabelFor(x => x.addressdetail.state)
    @Html.TextBoxFor(x => x.addressdetail.state)
    <br />
    <br />
    @Html.LabelFor(x => x.addressdetail.postalCode)
    @Html.TextBoxFor(x => x.addressdetail.postalCode)
    <br />
    <br />
    <h4>FINANCIAL DETAILS</h4>
    @Html.LabelFor(x => x.financialdetail.bankName)
    @Html.TextBoxFor(x => x.financialdetail.bankName)
    <br />
    <br />
    @Html.LabelFor(x => x.financialdetail.branch)
    @Html.TextBoxFor(x => x.financialdetail.branch)
    <br />
    <br />
    <b>Select Account Type</b>
    <br />
    <span> Savings : @Html.RadioButtonFor(x => x.financialdetail.accountType,"Savings")</span>
    <span> Current : @Html.RadioButtonFor(x => x.financialdetail.accountType,"Current")</span>
    <span> Salary : @Html.RadioButtonFor(x => x.financialdetail.accountType, "Salary")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.financialdetail.accountNumber)
    @Html.TextBoxFor(x => x.financialdetail.accountNumber)
    <br />
    <br />
    <b>Owned house or Rented house?</b>
    <br />
    <span> Owned : @Html.RadioButtonFor(x => x.financialdetail.ownOrRent,"Owned")</span>
    <span> Rented : @Html.RadioButtonFor(x => x.financialdetail.ownOrRent, "Rented")</span>
    <br />
    <br />
    <b>Any Ongoing Loan?</b>
    <br />
    <span> Yes : @Html.RadioButtonFor(x => x.financialdetail.currentLoan, "Yes")</span>
    <span> No : @Html.RadioButtonFor(x => x.financialdetail.currentLoan, "No")</span>
    <br />
    <br />
    <b>Currently Working?</b>
    <br />
    <span> Yes : @Html.RadioButtonFor(x => x.financialdetail.workingStatus, "Yes")</span>
    <span> No : @Html.RadioButtonFor(x => x.financialdetail.workingStatus, "No")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.financialdetail.monthlyIncome)
    @Html.TextBoxFor(x => x.financialdetail.monthlyIncome)
    <br />
    <br />
    <h4>VEHICAL DETAILS</h4>
    @Html.LabelFor(x => x.vehicaldetail.makeAndModel)
    @Html.TextBoxFor(x => x.vehicaldetail.makeAndModel)
    <br />
    <br />
    @Html.LabelFor(x => x.vehicaldetail.variant)
    @Html.TextBoxFor(x => x.vehicaldetail.variant)
    <br />
    <br />
    @Html.LabelFor(x => x.vehicaldetail.registeredDate)
    @Html.TextBoxFor(x => x.vehicaldetail.registeredDate, new { @type = "Date" })
    <br />
    <br />
    @Html.LabelFor(x => x.vehicaldetail.mileage)
    @Html.TextBoxFor(x => x.vehicaldetail.mileage)
    <br />
    <br />
    <b>Is your vehical Insured?</b>
    <br />
    <span> Yes : @Html.RadioButtonFor(x => x.vehicaldetail.insurance,"Yes" )</span>
    <span> No : @Html.RadioButtonFor(x => x.vehicaldetail.insurance,"No" )</span>
    <br />
    <br />
    @Html.LabelFor(x => x.vehicaldetail.registrationNumber)
    @Html.TextBoxFor(x => x.vehicaldetail.registrationNumber)
    <br />
    <br />
    <b>Which hand vehical you are using?</b>
    <br />
    <span> FirstHand : @Html.RadioButtonFor(x => x.vehicaldetail.nEWorSECONDHAND, "FirstHand")</span>
    <span> SecondHand : @Html.RadioButtonFor(x => x.vehicaldetail.nEWorSECONDHAND, "SecondHand")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.vehicaldetail.hpi)
    @Html.TextBoxFor(x => x.vehicaldetail.hpi)
    <br />
    <br />
    @Html.LabelFor(x => x.vehicaldetail.fullPrice)
    @Html.TextBoxFor(x => x.vehicaldetail.fullPrice)
    <br />
    <br />
    <h4>REQUESTED LOAN DETAILS</h4>
    <b>Select Loan Type</b>
    <br />
    <span> UsedCar : @Html.RadioButtonFor(x => x.requestedloandetail.carType,"UsedCar")</span>
    <span> NewCar : @Html.RadioButtonFor(x => x.requestedloandetail.carType, "NewCar")</span>
    <br />
    <br />
    @Html.LabelFor(x => x.requestedloandetail.loanAmount)
    @Html.TextBoxFor(x => x.requestedloandetail.loanAmount)
    <br />
    <br />
    <b>Select Term Duration</b>
    <br />
    <span> OneYear : @Html.RadioButtonFor(x => x.requestedloandetail.terms, "OneYear")</span>
    <span> TwoYear : @Html.RadioButtonFor(x => x.requestedloandetail.terms, "TwoYear")</span>
    <span> ThreeYear : @Html.RadioButtonFor(x => x.requestedloandetail.terms, "ThreeYear")</span>
    <span> FourYear : @Html.RadioButtonFor(x => x.requestedloandetail.terms, "FourYear")</span>
    <br />
    <br />
    <b>Select Prefered Payment</b>
    <br />
    <span> Monthly : @Html.RadioButtonFor(x => x.requestedloandetail.prefferedPayment, "Monthly")</span>
    <span> Quarterly : @Html.RadioButtonFor(x => x.requestedloandetail.prefferedPayment, "Quartly")</span>
    <span> Yearly : @Html.RadioButtonFor(x => x.requestedloandetail.prefferedPayment, "Yearly")</span>
    <br />
    <br />
    <b>Do you have a Co-signer?</b>
    <br />
    <span> Yes : @Html.RadioButtonFor(x => x.requestedloandetail.coSigner, "Yes")</span>
    <span> No : @Html.RadioButtonFor(x => x.requestedloandetail.coSigner, "No")</span>
    <br />
    <br />
    <b>If yes then fill below</b>
    <br />
    @Html.LabelFor(x => x.requestedloandetail.coSignerName)
    @Html.TextBoxFor(x => x.requestedloandetail.coSignerName)
    <br />
    <br />
    @Html.LabelFor(x => x.requestedloandetail.coSignerPhoneNo)
    @Html.TextBoxFor(x => x.requestedloandetail.coSignerPhoneNo)
    <br />
    <br />
    <input type="submit" value="submit" />
}